Fix/webmodeler resize
FlockOfBirds/time-series pull request #5
Opened 2017-07-25 13:25 UTC by djkwagala

2017-07-26 07:24 UTC, acellam requested changes

2017-07-26 07:24 UTC, mistaguy commented on src/TimeSeries.webmodeler.ts
> +        const modelerIFrame = this.getIframe();
Add space after declaring variables

2017-07-26 07:24 UTC, mistaguy commented on src/TimeSeries.webmodeler.ts
> +        const modelerIFrame = this.getIframe();
Add space after block of variable declaration

2017-07-26 07:24 UTC, mistaguy commented on src/components/Alert.ts
>          : null as any;
remove `as any`

2017-07-26 07:24 UTC, mistaguy commented on src/components/Alert.ts
> -        ? DOM.div({ className: "alert alert-danger widget-time-series-alert" }, props.message)
Make component generic by passing the  css class to allow it to be used for other alert types ie danger, success,

2017-07-26 07:24 UTC, mistaguy commented on src/components/NVD3LineChart.ts
> +    private svg: Element;
This is supposed to remain `svg` element

2017-07-26 07:24 UTC, mistaguy commented on src/components/NVD3LineChart.ts
> +            createElement("svg", { ref: node => this.svg = node })
when `svg` above is SVGElement, u can make the node be returned as SVGElement by doing this
`ref: node => this.svg = node as SVGElement`

2017-07-26 13:24 UTC, djkwagala commented on src/components/NVD3LineChart.ts
> +    private svg: Element;
Done

2017-07-26 13:24 UTC, djkwagala commented on src/components/NVD3LineChart.ts
> +            createElement("svg", { ref: node => this.svg = node })
Done

2017-07-27 05:02 UTC, djkwagala commented on src/TimeSeries.webmodeler.ts
> +        const modelerIFrame = this.getIframe();
not necessary

2017-07-27 05:03 UTC, djkwagala commented on src/TimeSeries.webmodeler.ts
> +        const modelerIFrame = this.getIframe();
The space is not necessary in this case.

2017-07-27 05:33 UTC, djkwagala commented on src/components/Alert.ts
>          : null as any;
done

2017-07-27 15:30 UTC, closed without merging